name: Sync Azure Blob (chunked) to Repo

on:
  workflow_dispatch:
    inputs:
      prefixes:
        description: "Space-separated prefixes (e.g., 'logs/2025-09-18/ images/'). Avoid '.' on large containers."
        required: true
        default: "logs/2025-09-18/"

permissions:
  contents: write

env:
  AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
  AZURE_CONTAINER: ${{ secrets.AZURE_CONTAINER }}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Free space before big transfers
      - name: Cleanup disk space before sync
        run: |
          sudo rm -rf /usr/share/dotnet /opt/ghc "/usr/local/share/boost" || true
          sudo docker system prune -af || true
          sudo apt-get clean || true
          df -h

      - name: Configure git author
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install AzCopy (v10)
        run: |
          set -e
          curl -sL https://aka.ms/downloadazcopy-v10-linux | tar -xz --strip-components=1
          sudo mv azcopy /usr/local/bin/azcopy
          azcopy --version

      - name: Sync prefixes (commit → push → evict from disk)
        env:
          PREFIXES: ${{ github.event.inputs.prefixes }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
        run: |
          set -euo pipefail
          : "${AZURE_STORAGE_KEY:?AZURE_STORAGE_KEY missing}"
          : "${AZURE_STORAGE_ACCOUNT:?AZURE_STORAGE_ACCOUNT missing}"
          : "${AZURE_CONTAINER:?AZURE_CONTAINER missing}"
          : "${PREFIXES:?No prefixes provided}"

          # Safety: syncing the entire container (".") will likely fill disk on shared runners
          if [ "$PREFIXES" = "." ]; then
            echo "::error::'.' (whole container) is not allowed on shared runners. Pass smaller prefixes (e.g., daily folders)."
            exit 1
          fi

          # Tune & auth
          ulimit -n 65536 || true
          export AZCOPY_ACCOUNT_KEY="${AZURE_STORAGE_KEY}"
          export AZCOPY_CONCURRENCY_VALUE=8
          export AZCOPY_LOG_LOCATION="$(pwd)/.azcopy-logs"
          mkdir -p "$AZCOPY_LOG_LOCATION"

          # Keep only one folder in the working tree at a time
          git sparse-checkout init --cone

          TMPROOT="$(mktemp -d)"
          trap 'rm -rf "$TMPROOT"' EXIT

          for p in $PREFIXES; do
            echo "==> Processing prefix: $p"

            # Evict everything except this prefix from the worktree (frees disk without committing deletions)
            git sparse-checkout set "$p"

            SRC_URL="https://${AZURE_STORAGE_ACCOUNT}.blob.core.windows.net/${AZURE_CONTAINER}/${p}"
            DEST_LOCAL="${TMPROOT}/${p}"
            TARGET_DIR="./$p"

            mkdir -p "$DEST_LOCAL" "$TARGET_DIR"

            # Download this chunk
            set +e
            azcopy copy "$SRC_URL" "$DEST_LOCAL" --recursive --log-level INFO
            AC_STATUS=$?
            set -e

            # Copy into repo
            rsync -a "$DEST_LOCAL"/ "$TARGET_DIR"/ || true

            # Stage and avoid >95MB files (GitHub hard-limit ~100MB)
            BIG=$(find "$TARGET_DIR" -type f -size +95M 2>/dev/null || true)
            git add "$TARGET_DIR"
            if [ -n "$BIG" ]; then
              echo "::warning::Skipping files >95MB in $p:"
              echo "$BIG" | sed 's/^/ - /'
              echo "$BIG" | xargs -r git reset -q
            fi

            if ! git diff --cached --quiet -- "$TARGET_DIR"; then
              git commit -m "Sync from Azure ${p} - $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
              git push
            else
              echo "No changes for ${p}."
            fi

            # Clean temp and show remaining space
            rm -rf "$DEST_LOCAL"
            df -h

            # Warn (don’t fail) on AzCopy issues to let later prefixes proceed
            if [ "$AC_STATUS" -ne 0 ]; then
              echo "::warning::AzCopy returned exit $AC_STATUS for ${p}. See logs in $AZCOPY_LOG_LOCATION"
              tail -n 100 "$(ls -t .azcopy-logs/*.log | head -n1)" || true
            fi
          done

          echo "Done. Only the last processed prefix remains in the workspace."
