name: Sync Azure Blob (public) to Repo

on:
  workflow_dispatch:
    inputs:
      prefixes:
        description: "Space-separated prefixes (e.g., logs/2025-09-18/ images/)"
        required: true
        default: "logs/ images/"

permissions:
  contents: write

env:
  AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
  AZURE_CONTAINER: ${{ secrets.AZURE_CONTAINER }}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Download and commit per chunk (with cleanup)
        env:
          PREFIXES: ${{ github.event.inputs.prefixes }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
        run: |
          set -euo pipefail
          export AZCOPY_ACCOUNT_KEY="$AZURE_STORAGE_KEY"
      
          TMPROOT="$(mktemp -d)"; trap 'rm -rf "$TMPROOT"' EXIT
          for p in $PREFIXES; do
            echo "==> Downloading prefix: $p"
            SRC_URL="https://${AZURE_STORAGE_ACCOUNT}.blob.core.windows.net/${AZURE_CONTAINER}/${p}"
            DEST_LOCAL="${TMPROOT}/${p}"
            mkdir -p "$DEST_LOCAL"
            azcopy copy "$SRC_URL" "$DEST_LOCAL" --recursive
            mkdir -p "./$p"; rsync -a "$DEST_LOCAL"/ "./$p"/ || true
            git add "$p"
            if ! git diff --cached --quiet -- "$p"; then
              git commit -m "Sync from Azure (${p}) - $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
              git push
            else
              echo "No changes for $p."
            fi
            rm -rf "$DEST_LOCAL"
          done
