name: Sync Azure Blob (chunked) to Repo

on:
  workflow_dispatch:
    inputs:
      prefixes:
        description: "Space-separated prefixes to fetch (e.g., logs/2025-09-18/ images/)"
        required: true
        default: "logs/"

permissions:
  contents: write  # to push back to repo
  id-token: write  # needed for workload identity/OIDC login

env:
  AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
  AZURE_CONTAINER: ${{ secrets.AZURE_CONTAINER }}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure git author
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Azure Login
        uses: azure/login@v2

      - name: Install AzCopy
        run: |
          curl -sL https://aka.ms/downloadazcopy-v10-linux | tar -xz --strip-components=1
          sudo mv azcopy /usr/local/bin/azcopy
          azcopy --version

      - name: Generate User Delegation SAS
        id: gensas
        run: |
          expiry=$(date -u -d "+2 hours" '+%Y-%m-%dT%H:%MZ')
          SAS=$(az storage container generate-sas \
            --account-name "$AZURE_STORAGE_ACCOUNT" \
            --name "$AZURE_CONTAINER" \
            --permissions rl \
            --expiry $expiry \
            --auth-mode login \
            -o tsv)
          echo "sas=$SAS" >> $GITHUB_OUTPUT

      - name: Sync chunks from Azure → repo
        env:
          SAS: ${{ steps.gensas.outputs.sas }}
          PREFIXES: ${{ github.event.inputs.prefixes }}
        run: |
          set -euo pipefail
          for p in $PREFIXES; do
            echo "==> Fetching $p"
            azcopy copy \
              "https://${AZURE_STORAGE_ACCOUNT}.blob.core.windows.net/${AZURE_CONTAINER}/${p}?${SAS}" \
              "./$p" --recursive
          done

      - name: Commit & Push
        run: |
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Sync from Azure (chunked) - $(date -u)"
            git push
          else
            echo "No changes to commit."
          fi
